spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tagtaxonomy}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_SCHEMA:public}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ${DB_SCHEMA:public}
    parameters:
      DB_SCHEMA: ${DB_SCHEMA:public}
  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: info
    org.springframework.web: info
